name: pipen_bloc
version: 1.1.0
description: "BLoC powerful tools"
homepage: "https://github.com/juanfelipepipen/pipen-bloc"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: any
  provider: any
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  async: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: